Feature get ga report 13 08
hungnguyengifttify/ff-gifttify pull request #1
Opened 2022-08-14 01:56 UTC by hatv1592

2022-08-14 10:37 UTC, hungnguyengifttify requested changes

2022-08-14 10:37 UTC, hungnguyengifttify commented on database/migrations/2022_08_13_034641_create_ga_campaign_reports_table.php
> +        });
Add giúp anh cái unique theo [campains_name, view_id, date_record] ở đây nhé

2022-08-14 10:37 UTC, hungnguyengifttify commented on routes/web.php
> +->name('order_management');
Sửa lại giúp a "->name('order_management')" thành "->name('report_ga_campaign');" vì cái name order_management đang dùng cho 1 controller khác

2022-08-14 10:37 UTC, hungnguyengifttify commented on app/Services/GoogleAnalytics.php
> +        $KEY_FILE_LOCATION = __DIR__ . '/../../service-account-credentials.json';
Gửi giúp a file này qua Zalo nhé

2022-08-14 10:37 UTC, hungnguyengifttify commented on app/Console/Commands/CrawlGoogleAnalyticCampaigns.php
> +<?php
Cronjob này anh sẽ set chạy every 2 minutes thì có được không em? và vị dụ nếu $from_time = '2022-8-1' và $to_time = '2022-8-5', anh muốn khi chạy sẽ có vòng for 5 lần để lưu vào db số liệu cho 5 ngày 1-8, 2-8, 3-8, 4-8, 5-8 cho một lần cronjob chạy được không em?

2022-08-14 10:37 UTC, hungnguyengifttify commented on app/Console/Commands/CrawlGoogleAnalyticCampaigns.php
> +        $date_record = '';
nếu $from_time = $to_time = 'today', $date_record cũng không được phép rỗng vì mình sẽ lưu db theo tường ngày

2022-08-15 03:02 UTC, hatv1592 commented on app/Console/Commands/CrawlGoogleAnalyticCampaigns.php
> +<?php
- Job et chạy 2 phút 1 lần để ấy dữ liệu hiên tại thì em thấy oke anh ạ.
- Còn chạy vòng for cho từng ngày thì hiện tại như code hiện tại thì chưa đc ạ. Sẽ tổng hợp từ ngày đến ngày chưa chưa theo kiểu vòng (Dùng cho báo cáo chung theo từ ngày đến ngày);

2022-08-15 09:57 UTC, hatv1592 commented on app/Console/Commands/CrawlGoogleAnalyticCampaigns.php
> +<?php
Hiện em đã update lại craw theo từng ngày lúc set anh nhé!

2022-08-15 09:57 UTC, hatv1592 commented on routes/web.php
> +->name('order_management');
Đã update lại ạ. View này demo data để show ra ạ.

2022-08-15 10:06 UTC, hungnguyengifttify approved these changes

2022-08-15 10:12 UTC, merged